### ISSUE TITLE
Getting all the posts, but bring the followers posts to the start

### ISSUE THREAD

**Issue by Xoshbin** [LaravelDaily/Laravel-Facebook-Feed-Simulate#1]
Hi, Thank you for this demo, it helped a lot in learning a lot of new stuff, from factories to orderBy calculations.
Now when I'm testing, the feed is empty if I don't follow anyone. I was wondering if it's possible to have mixed posts of those that I have followed and those I didn't follow, and bringing to see posts that I follow their authors to the beginning, I tried to manipulate the query but instead of getting what I want I ruined it 😊.
And in another situation what if you don't follow anyone, at least there should be some posts.
Right now for unauthenticated users, I'm using another query. solved this part by checking if user is logged in (easy).
but what if I logged in and I haven't followed anyone?
I know there's workarounds like when the user registers you suggest some authors or channels to follow. But what I want is on the same query that we already have if it's technically possible.
Thank you

**Comment by PovilasKorop** [comment]
@Xoshbin probably not, and probably I wouldn't do it on the same query. Totally fresh users need a totally different logic on "onboarding" experience, maybe even the page should look differently, like a wizard with steps.

**Comment by Xoshbin** [comment]
Ok, forget new users.
Now the query only returns those posts that I followed their authors. There should be a way to add other posts to the feed, otherwise, the user will be stuck with those users that are already following and won't be able to follow new authors or users. I mean just like Facebook, sometimes there's a post in your feed that you didn't follow. the author and sometimes there's a post labeled "recommended".
Thank you for replying

**Comment by PovilasKorop** [comment]
@Xoshbin well, if you want to improve this project for that behavior, feel free, it's open-source! :) 

Sorry, I don't have free time now to improve this demo, it was just a demo for the video, without plans to create a full social network.

**Comment by Xoshbin** [comment]
Sure, Thank you.
I will try, if I found some way I will do a PR
